services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_frontend
    ports:
      - "3000:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    command: ["yarn", "dev", "--host"]

  db:
    image: mysql:8
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: news_aggregator
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p$${MYSQL_ROOT_PASSWORD} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      db:
        condition: service_healthy

  webserver:
    image: nginx:alpine
    container_name: nginx_server
    depends_on:
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
      - ./backend/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  scheduler:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_scheduler
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
    command: ["sh", "-c", "while :; do php artisan schedule:run >> /dev/null 2>&1; sleep 60; done"]

volumes:
  db_data:
